# Generated by Django 4.2.3 on 2023-07-20 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_inkinddonation_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='number',
            new_name='NumberOfAchievements',
        ),
    ]
