# Generated by Django 4.2.3 on 2023-08-07 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_eventregister_nav_alter_about_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achivment',
            new_name='Achievements',
        ),
        migrations.RenameField(
            model_name='achievements',
            old_name='Test',
            new_name='Year',
        ),
    ]
